version: '2'
services:
  im_db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: 'db_pwd'
      POSTGRES_USER: 'db_user'
      PGDATA: '/data/pgdata'
      POSTGRES_DB: 'im_docker'
    volumes:
      - ./dbdata:/data/pgdata
    ports:
      - "6100:5432"
  im_redis:
    image: redis
    ports:
      - "7379:6379"
  im_rest_backend:
    environment:
      DB_CONNECTION: postgresql+psycopg2://db_user:db_pwd@im_db/im_docker
      REDIS_CONNECTION: redis://im_redis      
    build: ./backend
    ports: 
      - "9000:8000"
      - "2022:22"
    volumes:
      - ../.:/app
    depends_on:
      - im_db
      - im_redis
    command: ["./wait-for-it.sh", "db:6000"]
  im_rest_frontend:
    build: ./frontend
    ports:
      - "9010:9010"
    volumes:
      - ../frontend:/app
    depends_on:
      - im_rest_backend
  nginx:
    build: ./nginx
    ports:
      - "8889:8889"
    depends_on:
      - im_rest_backend
      - im_rest_frontend

